server:
  port: 9003
spring:
  application:
    name: tensquare-qa #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.224.35.86:3306/tensquare_qa?characterEncoding=UTF8&useSSL=false
    username: root
    password: df-21
  jpa:
    database: MySQL
    show-sql: true
jwt:
  config:
    key: itcast
    ttl: 360000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true