server:
  port: 9010
spring:
  application:
    name: tensquare-friend # 指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.224.35.86:3306/tensquare_friend?characterEncoding=UTF-8&serverTimezone=UTC&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: df-21
  jpa:
    database: mysql
    show-sql: true
jwt:
  config:
    key: itcast
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true