server: 
  port: 9005
spring: 
  application:  
    name: tensquare-gathering #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/tensquare_gathering?characterEncoding=UTF8
    username: root
    password: 111111
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: localhost
    password:
    port: 6379